### ISSUE TITLE
如果是路由打开的页面，点击浏览器的回退按钮或是键盘的backspace返回上一个页面，弹出层不关闭

### ISSUE THREAD

**Issue by anna647** [WorktileTech/angular-wt-pbox#4]
这个小插件还挺好用的，之前都没发现这个问题。我们的页面是用路由跳转的，如果打开了bpox不关闭，返回到上一个页面它是不会关的，除非再点击一下，这是神马问题

**Comment by why520crazy** [comment]
因为单页程序，所以浏览器的回退并不会刷新页面，只是 ui-view 区域替换，这个弹出的层只有点击了 document区域或者调用关闭时间才会关闭，所以浏览器的回退不会关闭。

这种情况其实可以不用管的，如果想解决可以试试绑定 元素的  remove 方法，当触发弹出的元素 destroy 后关闭 pop

**Comment by anna647** [comment]
这个问题是解决啦，谢谢。但是如果是读取input的值是获取不到的，给ng-model赋值或是修改它的值都可以在view中显示出来，但如果仅仅是读取的话就是undefined，这又是什么问题啊？

**Comment by why520crazy** [comment]
@anna647 你描述的问题和这个 Issue 没有关系吧，感觉好像是获取的地方和页面ng-model的地方是2个scope，然后 ng-model=“xxxx” 是直接绑定在scope下的字符串或者值类型， 应该是原型继承的问题，试着修改成 ng-model=“vm.xxx”

看下 http://www.ngnice.com/posts/2c8208220edb94  Q6

**Comment by anna647** [comment]
修改之后就OK了，谢谢
